### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by Pannoniae** [schombert/Open-V2#9]
I've tried to compile this, and for some reason, neither boost nor freetype (possibly other libraries as well) are referenced. I am using Windows 10, VS2017.

Sorry if I am/were stupid.

**Comment by schombert** [comment]
Sorry, but unless you can be more specific I can't help you. The various libraries are "referenced" in the common project properties file.

**Comment by Pannoniae** [comment]
I'll try again a bit later and give exact details. Sorry.
